#! /usr/bin/env sh
DATE=`date +%Y%m%d%H%M%S`

MIGRATION_NAME=$1

if [ -z $MIGRATION_NAME ]
then
  echo "You must supply a migration name"
  exit
fi

touch "migrations/${DATE}_${MIGRATION_NAME}.up.sql"
touch "migrations/${DATE}_${MIGRATION_NAME}.down.sql"
